name = "noaagprof"

[architecture]
name = "EncoderDecoder"
preset = "EfficientNetV2-L"
skip_connections=true

[architecture.encoder]
channels = [29, 58, 77, 154, 192, 307]
downsampling_factors = [1, 2, 2, 2, 2]
stage_depths = [1, 3, 3, 4, 6, 21]
block_factory = [
    "InvertedBottleneck",
    "InvertedBottleneck",
    "InvertedBottleneck",
    "InvertedBottleneck",
    "InvertedBottleneck",
    "InvertedBottleneck",
]
block_factory_args = [
    {activation_factory="GELU", normalization_factory="RMSNormFirst", expansion_factor=1, excitation_ratio=0.0, fused=true, anti_aliasing=false},
    {activation_factory="GELU", normalization_factory="RMSNormFirst", expansion_factor=4, excitation_ratio=0.0, fused=true, anti_aliasing=false},
    {activation_factory="GELU", normalization_factory="RMSNormFirst", expansion_factor=4, excitation_ratio=0.0, fused=true, anti_aliasing=false},
    {activation_factory="GELU", normalization_factory="RMSNormFirst", expansion_factor=4, excitation_ratio=0.25, anti_aliasing=false},
    {activation_factory="GELU", normalization_factory="RMSNormFirst", expansion_factor=6, excitation_ratio=0.25, anti_aliasing=false},
    {activation_factory="GELU", normalization_factory="RMSNormFirst", expansion_factor=6, excitation_ratio=0.25, anti_aliasing=false},
]

[architecture.decoder]
channels = [192, 154, 77, 58, 48]
upsampling_factors = [2, 2, 2, 2, 1]
stage_depths = [6, 4, 3, 3, 1]
block_factory = [
    "InvertedBottleneck",
    "InvertedBottleneck",
    "InvertedBottleneck",
    "InvertedBottleneck",
    "InvertedBottleneck",
]
block_factory_args = [
    {activation_factory="GELU", normalization_factory="RMSNormFirst", expansion_factor=6, excitation_ratio=0.25, anti_aliasing=false},
    {activation_factory="GELU", normalization_factory="RMSNormFirst", expansion_factor=4, excitation_ratio=0.25, anti_aliasing=false},
    {activation_factory="GELU", normalization_factory="RMSNormFirst", expansion_factor=4, excitation_ratio=0.0, fused=true, anti_aliasing=false},
    {activation_factory="GELU", normalization_factory="RMSNormFirst", expansion_factor=4, excitation_ratio=0.0, fused=true, anti_aliasing=false},
    {activation_factory="GELU", normalization_factory="RMSNormFirst", expansion_factor=1, excitation_ratio=0.0, fused=true, anti_aliasing=false},
]

[architecture.head]
individual = true

[architecture.head.default]
kind="BasicConv"
depth=4

[input.amsr2]
n_features=16
normalize="minmax"

[output.surface_precip]
kind = "Quantiles"
quantiles = 32

[output.precipitation_type]
kind = "Classification"
n_classes = 4

[output.convective]
kind = "Detection"

[output.convective_precip]
kind = "Quantiles"
quantiles = 32

[output.rain_water_content]
kind = "Quantiles"
shape = [28,]
quantiles = 32

[output.snow_water_content]
kind = "Quantiles"
shape = [28,]
quantiles = 32

[output.latent_heating]
kind = "Quantiles"
shape = [28,]
quantiles = 32

[output.snow_water_path]
kind = "Quantiles"
quantiles = 32

[output.rain_water_path]
kind = "Quantiles"
quantiles = 32
