name = "noaagprof_fixed_sp_only"

[architecture]
name = "EncoderDecoder"
preset = "EfficientNetV2-S"
skip_connections=true

[architecture.encoder]
channels = [24, 48, 64, 128, 160, 256]
downsampling_factors = [1, 2, 2, 2, 2]
stage_depths = [1, 2, 2, 3, 4, 15]
block_factory = [
    "InvertedBottleneck",
    "InvertedBottleneck",
    "InvertedBottleneck",
    "InvertedBottleneck",
    "InvertedBottleneck",
    "InvertedBottleneck",
]
block_factory_args = [
    {activation_factory="GELU", normalization_factory="RMSNormFirst", expansion_factor=1, excitation_ratio=0.0, fused=true, anti_aliasing=false},
    {activation_factory="GELU", normalization_factory="RMSNormFirst", expansion_factor=4, excitation_ratio=0.0, fused=true, anti_aliasing=false},
    {activation_factory="GELU", normalization_factory="RMSNormFirst", expansion_factor=4, excitation_ratio=0.0, fused=true, anti_aliasing=false},
    {activation_factory="GELU", normalization_factory="RMSNormFirst", expansion_factor=4, excitation_ratio=0.25, anti_aliasing=false},
    {activation_factory="GELU", normalization_factory="RMSNormFirst", expansion_factor=6, excitation_ratio=0.25, anti_aliasing=false},
    {activation_factory="GELU", normalization_factory="RMSNormFirst", expansion_factor=6, excitation_ratio=0.25, anti_aliasing=false},
]

[architecture.decoder]
channels = [160, 128, 64, 48, 24]
upsampling_factors = [2, 2, 2, 2, 1]
stage_depths = [4, 3, 2, 2, 1]
block_factory = [
    "InvertedBottleneck",
    "InvertedBottleneck",
    "InvertedBottleneck",
    "InvertedBottleneck",
    "InvertedBottleneck",
]
block_factory_args = [
    {activation_factory="GELU", normalization_factory="RMSNormFirst", expansion_factor=6, excitation_ratio=0.25, anti_aliasing=false},
    {activation_factory="GELU", normalization_factory="RMSNormFirst", expansion_factor=4, excitation_ratio=0.25, anti_aliasing=false},
    {activation_factory="GELU", normalization_factory="RMSNormFirst", expansion_factor=4, excitation_ratio=0.0, fused=true, anti_aliasing=false},
    {activation_factory="GELU", normalization_factory="RMSNormFirst", expansion_factor=4, excitation_ratio=0.0, fused=true, anti_aliasing=false},
    {activation_factory="GELU", normalization_factory="RMSNormFirst", expansion_factor=1, excitation_ratio=0.0, fused=true, anti_aliasing=false},
]

[architecture.head]
individual = true

[architecture.head.default]
kind="BasicConv"
activation_factory="GELU"
normalization_factory="RMSNormFirst"
depth=4

[input.amsr2]
n_features=16
normalize="minmax"

[output.surface_precip]
kind = "Quantiles"
quantiles = 32
