[stage_1]
dataset_module = "noaagprof.training_data"
training_dataset = "TrainingDataset"
training_dataset_args = {paths=["/gdata1/simon/noaagprof/training_data_cmb"]}
validation_dataset_args = {paths=["/gdata1/simon/noaagprof/validation_data_cmb"]}
n_epochs = 60
optimizer = "AdamW"
optimizer_args = {lr = 5e-4}
scheduler = "CosineAnnealingLR"
scheduler_args = {T_max = 60}
input_datasets = ["cpcir"]
reference_datasets = ["cmb_and_mrms"]
batch_size = 3
accumulated_grad_batches = 2
metrics = ["Bias", "MSE", "CorrelationCoef"]
scene_size = 256
n_dataloader_workers = 4

[stage_2]
dataset_module = "noaagprof.training_data"
training_dataset = "TrainingDataset"
training_dataset_args = {paths=["/gdata1/simon/noaagprof/training_data_cmb"]}
validation_dataset_args = {paths=["/gdata1/simon/noaagprof/validation_data_cmb"]}
n_epochs = 60
optimizer = "AdamW"
optimizer_args = {lr = 1e-4}
scheduler = "CosineAnnealingLR"
scheduler_args = {T_max = 60}
input_datasets = ["cpcir"]
reference_datasets = ["cmb_and_mrms"]
batch_size = 3
accumulated_grad_batches = 2
metrics = ["Bias", "MSE", "CorrelationCoef"]
reuse_optimizer = true
scene_size = 256
n_dataloader_workers = 4
