tile_size = [128, 64]
spatial_overlap = 16
input_loader = "noaagprof.InputLoader"
input_loader_args = {config="3d"}

[retrieval_output.surface_precip]
surface_precip = "ExpectedValue"
surface_precip_terciles = {retrieval_output="Quantiles", tau=[0.33, 0.66]}
probability_of_precipitation = {retrieval_output="ExceedanceProbability", threshold=1e-3}

[retrieval_output.convective_precip]
convective_precip = "ExpectedValue"

[output.rain_water_path]
rain_water_path = "ExpectedValue"

[output.ice_water_path]
ice_water_path = "ExpectedValue"

[output.cloud_water_path]
cloud_water_path = "ExpectedValue"

[output.rain_water_content]
rain_water_content = "ExpectedValue"

[output.snow_water_content]
snow_water_content = "ExpectedValue"

[output.cloud_water_content]
cloud_water_content = "ExpectedValue"

[output.latent_heat]
latent_heating = "ExpectedValue"
